name: Continuous Integration

# run for pull requests and pushes to master branch
on:
  push:
    branches:
      - 'master'
  pull_request:

# always use pretty colors
env:
  CARGO_TERM_COLOR: always

jobs:
  # check formatting (use nightly rustfmt)
  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly && rustup component add rustfmt --toolchain nightly && rustup default nightly
      - run: cargo fmt --check

  # check style (using clippy)
  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: cargo clippy

  # build and test code
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
